define({
    type_attributes: [
        ['internship', {
            'title': 'Internship',
            'attributes':
                ['status', 'startdate', 'enddate', 'description', 'url',
                 'internship-type',
                 'facility',
                 'facility-affiliation',
                 'cnrs-inserm-unit-code',
                 'street-address',
                 'city',
                 'country',
                ],
        }],
        ['skill', {
            'title': 'Skill',
            'attributes': ['description', 'url'],
        }],
        ['interest', {
            'title': 'Interesst',
            'attributes': ['description', 'url'],
        }],
        ['person', {
            'title': 'Student',
            'attributes': ['description', 'url', 'email', 'image-url'],
        }],
        ['resource', {
            'title': 'Mentor',
            'attributes': ['description', 'url', 'organisation', 'image-url'],
        }],
        ['club', {
            'title': 'Club',
            'attributes': ['description', 'url'],
        }]
    ],
    attribute_titles: {
        'name': 'Name',
        'type': 'Type',
        'description': 'Description',
        'url': 'URL',
        'status': 'Status',
        'startdate': 'Start Date',
        'enddate': 'End Date',
        'internship-type': 'Internship Type',
        'facility': 'Lab/Company',
        'facility-affiliation': 'Lab affiliation',
        'cnrs-inserm-unit-code': 'CNRS / INSERM unit code',
        'street-address': 'Street address',
        'city': 'City',
        'email': 'Email',
        'image-url':'Image URL',
        'country': 'Country',
    }, 
    attribute_ui:{
        'name': 'input',
        'type': 'type',
        'description': 'textarea',
        'url': 'url',
        'status': 'input',
        'startdate': 'Start Date',
        'enddate': 'End Date',
        'internship-type': 'input',
        'facility': 'input',
        'facility-affiliation': 'input',
        'cnrs-inserm-unit-code': 'input',
        'street-address': 'input',
        'city': 'input',
        'email': 'email',
        'image-url':'image',
        'country': 'input',
    },
});
