#!/usr/bin/python

import os
from subprocess import Popen

from util import versions, check_output

if __name__ == '__main__':
    if versions.by_tag() != versions.version:
        print("non matching tag and files. tag={}, files={}".format(
            versions.by_tag(), versions.version))
        raise SystemExit
    full_commits = check_output('git log --oneline v-{}..'.format(versions.version).split()).split('\n')
    commits = [x.split(' ', 1)[1] for x in full_commits if x.strip() != '']
    versions.bump_version(debian_changelog=commits)
    Popen(args='{} {}'.format(os.environ.get('EDITOR', 'vim'), versions.debian_changelog_path).split()).wait()
    check_output('git add {}'.format(' '.join(versions.filenames)).split())
    check_output(['git', 'commit', '-m', 'version {}'.format(versions.version)])
    check_output(['git', 'tag', '-a', 'v-{}'.format(versions.version),
                  '-m', "version {}".format(versions.version)])
