#!/usr/bin/python

"""
upgrade debian package, run from a Fedora machine with working systemd-nspawn
with a machine called rzdeb.
"""

import argparse
import os
import subprocess
import re
import json
import sys

from util import versions


NSPAWN_MACHINE = 'rzdeb'
CHROOT = '{}/rhizi/rhizi-machines/debian7-chroot/'.format(os.environ['HOME'])
REMOTE_USER = 'root'
RHIZI_SOURCE_REPO = os.path.realpath(os.path.join(os.path.dirname(__file__), '..'))
SSH_KEY_DIR = os.path.realpath(os.path.join(RHIZI_SOURCE_REPO, '..', 'ssh-keys'))
# Assume identity of user running this script and in nspawn user
USER = os.getuid()


# set via command line arguments
remote_host = None
dryrun = False
dryrun_install = True


def check_call(oneliner):
    if not isinstance(oneliner, list):
        args = oneliner.split()
    else:
        args = oneliner
    print('calling {}'.format(repr(args)))
    print('oneliner {}'.format(' '.join(args)))
    if not dryrun:
        subprocess.check_call(args)


def clone(source_repo, target_path):
    check_call('git clone {} {}'.format(source_repo, target_path))


def chroot(path, oneliner, user=USER):
    check_call(['sudo', 'systemd-nspawn', '-u', str(user),
                '-M', NSPAWN_MACHINE, '-D', CHROOT, "bash", "-c",
                'cd {}; {}'.format(path, oneliner)])


def rmdir(path):
    check_call(['rm', '-Rf', path])


def keyfile(host):
    return os.path.join(SSH_KEY_DIR, '{}.rsa'.format(host))


def scp(source, target):
    check_call(['scp', '-i', keyfile(remote_host), source, '{}@{}:{}'.format(REMOTE_USER, remote_host, target)])


def ssh(*args):
    check_call(['ssh', '-i', keyfile(remote_host), '{}@{}'.format(REMOTE_USER, remote_host)] + list(args))


def install_deb(filename):
    if dryrun_install:
        ssh('ls', '-l', filename)
        ssh('dpkg', '-l', '|', 'grep', 'mux')
    else:
        ssh('dpkg','-i', filename)


def build_deb():
    chroot('/home/rhizi', 'ant -f build.ant pkg-deb__mux')


def install_locally(filename):
    chroot('/home/rhizi', 'dpkg -i {}'.format(filename), user='root')


def main():
    versions.ensure_synced()

    chroot_rhizi = os.path.join(CHROOT, 'home', 'rhizi')
    deb_filename = 'rhizi-mux_{}_amd64.deb'.format(versions.debian)
    deb_relative_path = os.path.join('home', 'rhizi', 'build',
                                     'deb-pkg__rhizi-mux', deb_filename)
    deb_chroot_fullpath = '/' + deb_relative_path
    deb_local_fullpath = os.path.join(CHROOT, deb_relative_path)

    rmdir(chroot_rhizi)
    assert not os.path.exists(deb_local_fullpath)
    clone(RHIZI_SOURCE_REPO, chroot_rhizi)
    build_deb()
    assert os.path.exists(deb_local_fullpath), "missing {}".format(deb_local_fullpath)
    install_locally(deb_chroot_fullpath)
    scp(source=deb_local_fullpath, target=deb_filename)
    install_deb(deb_filename)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--real', action='store_true', default=False)
    parser.add_argument('--dryrun', action='store_true', default=False)
    parser.add_argument('--host', required=True)
    args = parser.parse_args(sys.argv[1:])
    dryrun = args.dryrun
    dryrun_install = not args.real
    remote_host = args.host
    main()
